# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_transform.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'image_transform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15image_transform.proto\";\n\x0bsourceImage\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\"@\n\x10transformedImage\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x0e\n\x06height\x18\x03 \x01(\x02\"\x1f\n\rVectorRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\" \n\x0eVectorResponse\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x32n\n\rEncodeService\x12,\n\tGetEncode\x12\x0c.sourceImage\x1a\x11.transformedImage\x12/\n\x0c\x45ncodeVector\x12\x0e.VectorRequest\x1a\x0f.VectorResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_transform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOURCEIMAGE']._serialized_start=25
  _globals['_SOURCEIMAGE']._serialized_end=84
  _globals['_TRANSFORMEDIMAGE']._serialized_start=86
  _globals['_TRANSFORMEDIMAGE']._serialized_end=150
  _globals['_VECTORREQUEST']._serialized_start=152
  _globals['_VECTORREQUEST']._serialized_end=183
  _globals['_VECTORRESPONSE']._serialized_start=185
  _globals['_VECTORRESPONSE']._serialized_end=217
  _globals['_ENCODESERVICE']._serialized_start=219
  _globals['_ENCODESERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
