postgresql:
  username: postgres
  password: mysecurepassword
  database: postgres
  port: 5432

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""  # ใช้ default StorageClass ถ้าเว้นว่าง

service:
  type: ClusterIP
