apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus
  namespace: argocd  # namespace ของ Argo CD
spec:
  project: default
  source:
    repoURL: https://github.com/milvus-io/milvus-helm.git  # repo Helm chart ของ Milvus
    targetRevision: v2.3.21  # version ของ chart
    chart: milvus
    helm:
      values: |
        image:
          all:
            repository: milvusdb/milvus
            tag: v2.3.21

        cluster:
          enabled: false

        pulsar:
          enabled: false

        etcd:
          replicaCount: 1
          persistence:
            enabled: true
            size: 1Gi
          nodeSelector:
            kubernetes.io/hostname: notroot-thinkcentre-m710q

        minio:
          enabled: true
          mode: standalone
          replicaCount: 1
          persistence:
            enabled: true
            size: 2Gi
          nodeSelector:
            kubernetes.io/hostname: notroot-thinkcentre-m710q
          provisioning:
            enabled: true
            nodeSelector:
              kubernetes.io/hostname: notroot-thinkcentre-m710q

        standalone:
          enabled: true
          nodeSelector:
            kubernetes.io/hostname: notroot-thinkcentre-m710q
          service:
            type: NodePort
          persistence:
            enabled: true
            size: 50Gi
            storageClass: "local-path"
            accessMode: ReadWriteOnce

        persistence:
          storageClass: "local-path"

  destination:
    server: https://kubernetes.default.svc
    namespace: milvus  # namespace ที่คุณต้องการ deploy Milvus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
